@extends('layouts.app')
@section('title',$contact->exists?'Uredi kontakt':'Novi kontakt')
@section('content')
<div class="form-shell"><x-page-header eyebrow="KONTAKTI" :title="$contact->exists?'Uredi kontakt':'Novi kontakt'" description="Kontekst osobe vrijedi više od pune adresne knjige." /><x-form-errors />
<form method="POST" action="{{ $contact->exists?route('contacts.update',$contact):route('contacts.store') }}">@csrf @if($contact->exists)@method('PUT')@endif
<section class="form-card"><div class="form-section-head"><span>01</span><div><h2>Osoba</h2><p>Identitet i uloga kontakta</p></div></div><div class="form-grid"><div class="field"><span>Ime <em>*</em></span><input name="first_name" value="{{ old('first_name',$contact->first_name) }}" required></div><div class="field"><span>Prezime <em>*</em></span><input name="last_name" value="{{ old('last_name',$contact->last_name) }}" required></div><div class="field"><span>Tvrtka</span><select name="company_id"><option value="">— Bez tvrtke —</option>@foreach($companies as $company)<option value="{{ $company->id }}" @selected((string)old('company_id',$contact->company_id)===(string)$company->id)>{{ $company->name }}</option>@endforeach</select></div><div class="field"><span>Radna pozicija</span><input name="job_title" value="{{ old('job_title',$contact->job_title) }}"></div><div class="field"><span>Status <em>*</em></span><select name="status">@foreach(App\Enums\ContactStatus::cases() as $s)<option value="{{ $s->value }}" @selected(old('status',$contact->status?->value??'new')===$s->value)>{{ $s->label() }}</option>@endforeach</select></div><div class="field"><span>Rođendan</span><input type="date" name="birthday" value="{{ old('birthday',$contact->birthday?->format('Y-m-d')) }}"></div></div></section>
<section class="form-card"><div class="form-section-head"><span>02</span><div><h2>Kontaktni kanali</h2><p>Direktna komunikacija</p></div></div><div class="form-grid"><div class="field"><span>E-mail</span><input type="email" name="email" value="{{ old('email',$contact->email) }}"></div><div class="field"><span>Telefon</span><input name="phone" value="{{ old('phone',$contact->phone) }}"></div><div class="field full"><span>LinkedIn URL</span><input type="url" name="linkedin_url" value="{{ old('linkedin_url',$contact->linkedin_url) }}" placeholder="https://linkedin.com/in/..."></div><div class="field full"><span>Bilješke</span><textarea name="notes">{{ old('notes',$contact->notes) }}</textarea></div></div></section>
<div class="form-footer"><a class="ghost-btn" href="{{ $contact->exists?route('contacts.show',$contact):route('contacts.index') }}">Odustani</a><button class="primary-btn">{{ $contact->exists?'Spremi promjene':'Izradi kontakt' }} →</button></div></form></div>
@endsection
