@extends('layouts.app')
@section('title',$company->exists?'Uredi tvrtku':'Nova tvrtka')
@section('content')
<div class="form-shell"><x-page-header eyebrow="TVRTKE" :title="$company->exists?'Uredi tvrtku':'Nova tvrtka'" description="Zabilježite ključne poslovne podatke i kontekst odnosa." />
<x-form-errors /><form method="POST" action="{{ $company->exists?route('companies.update',$company):route('companies.store') }}">@csrf @if($company->exists)@method('PUT')@endif
<section class="form-card"><div class="form-section-head"><span>01</span><div><h2>Osnovni podaci</h2><p>Identitet i status tvrtke</p></div></div><div class="form-grid">
<div class="field"><span>Naziv tvrtke <em>*</em></span><input name="name" value="{{ old('name',$company->name) }}" required></div><div class="field"><span>Status <em>*</em></span><select name="status" required>@foreach(App\Enums\CompanyStatus::cases() as $s)<option value="{{ $s->value }}" @selected(old('status',$company->status?->value??'lead')===$s->value)>{{ $s->label() }}</option>@endforeach</select></div>
<div class="field"><span>Industrija</span><input name="industry" value="{{ old('industry',$company->industry) }}" placeholder="npr. SaaS, maloprodaja"></div><div class="field"><span>Web stranica</span><input type="url" name="website" value="{{ old('website',$company->website) }}" placeholder="https://"></div>
</div></section>
<section class="form-card"><div class="form-section-head"><span>02</span><div><h2>Kontakt i lokacija</h2><p>Kako doći do organizacije</p></div></div><div class="form-grid"><div class="field"><span>E-mail</span><input type="email" name="email" value="{{ old('email',$company->email) }}"></div><div class="field"><span>Telefon</span><input name="phone" value="{{ old('phone',$company->phone) }}"></div><div class="field"><span>Grad</span><input name="city" value="{{ old('city',$company->city) }}"></div><div class="field"><span>Država (ISO)</span><input name="country" maxlength="2" value="{{ old('country',$company->country?:'HR') }}" required></div></div></section>
<section class="form-card"><div class="form-section-head"><span>03</span><div><h2>Poslovni profil</h2><p>Veličina i dodatni kontekst</p></div></div><div class="form-grid"><div class="field"><span>Broj zaposlenih</span><input type="number" min="0" name="employees" value="{{ old('employees',$company->employees) }}"></div><div class="field"><span>Godišnji prihod (€)</span><input type="number" min="0" step="0.01" name="annual_revenue" value="{{ old('annual_revenue',$company->annual_revenue) }}"></div><div class="field full"><span>Bilješke</span><textarea name="notes">{{ old('notes',$company->notes) }}</textarea></div></div></section>
<div class="form-footer"><a class="ghost-btn" href="{{ $company->exists?route('companies.show',$company):route('companies.index') }}">Odustani</a><button class="primary-btn">{{ $company->exists?'Spremi promjene':'Izradi tvrtku' }} →</button></div></form></div>
@endsection
