@extends('layouts.app')
@section('title',$company->name)
@section('content')
<x-page-header eyebrow="TVRTKE / DETALJI" :title="$company->name"><a class="secondary-btn" href="{{ route('companies.edit',$company) }}">Uredi</a><a class="primary-btn" href="{{ route('deals.create',['company'=>$company->id]) }}">＋ Novi deal</a></x-page-header>
<div class="show-layout"><section class="detail-card"><div class="hero-identity"><span class="hero-avatar">{{ strtoupper(substr($company->name,0,2)) }}</span><div><x-status :status="$company->status" /><h2>{{ $company->name }}</h2><p>{{ $company->industry ?: 'Industrija nije unesena' }}</p></div></div><div class="detail-grid"><div class="detail-item"><small>E-mail</small><a href="mailto:{{ $company->email }}">{{ $company->email ?: '—' }}</a></div><div class="detail-item"><small>Telefon</small><strong>{{ $company->phone ?: '—' }}</strong></div><div class="detail-item"><small>Web</small>@if($company->website)<a target="_blank" href="{{ $company->website }}">{{ $company->website }}</a>@else<strong>—</strong>@endif</div><div class="detail-item"><small>Lokacija</small><strong>{{ $company->city ?: '—' }}{{ $company->country?', '.$company->country:'' }}</strong></div><div class="detail-item"><small>Zaposlenih</small><strong>{{ $company->employees ? number_format($company->employees,0,',','.') : '—' }}</strong></div><div class="detail-item"><small>Godišnji prihod</small><strong>{{ $company->annual_revenue?'€'.number_format($company->annual_revenue,2,',','.'):'—' }}</strong></div></div><div class="notes-box"><h3>Bilješke</h3><p>{{ $company->notes ?: 'Nema zabilježenih bilješki.' }}</p></div></section><aside><section class="side-card"><h3>Kontakti <small>({{ $company->contacts->count() }})</small></h3><div class="related-list">@forelse($company->contacts->take(6) as $contact)<a href="{{ route('contacts.show',$contact) }}"><span><strong>{{ $contact->full_name }}</strong><small>{{ $contact->job_title ?: 'Bez pozicije' }}</small></span><span>→</span></a>@empty<p class="side-empty">Još nema povezanih kontakata.</p>@endforelse</div></section><section class="side-card"><h3>Dealovi <small>({{ $company->deals->count() }})</small></h3><div class="related-list">@forelse($company->deals->take(6) as $deal)<a href="{{ route('deals.show',$deal) }}"><span><strong>{{ $deal->title }}</strong><small>{{ $deal->stage->label() }}</small></span><strong>{{ $deal->currency }} {{ number_format($deal->value,0,',','.') }}</strong></a>@empty<p class="side-empty">Još nema povezanih dealova.</p>@endforelse</div><div class="danger-zone"><span>Zapis više nije potreban?</span><form method="POST" action="{{ route('companies.destroy',$company) }}" onsubmit="return confirm('Arhivirati tvrtku?')">@csrf @method('DELETE')<button class="danger-btn">Arhiviraj</button></form></div></section></aside></div>

<section class="panel detail-activity">
    <div class="panel-head"><div><p class="eyebrow">AKTIVNOSTI</p><h2>Bilješke i zadaci</h2></div><a href="{{ route('activities.index', ['company_id' => $company->id, 'scope' => 'all']) }}">Sve aktivnosti →</a></div>
    <x-activity-form :company-id="$company->id" compact placeholder="Npr. Nazvati za ponudu…" />
    @if ($openTasks->isNotEmpty())
        <h3 class="sub-heading">Otvoreni zadaci ({{ $openTasks->count() }})</h3>
        <x-timeline :items="$openTasks" :show-context="false" />
    @endif
    <h3 class="sub-heading">Povijest</h3>
    <x-timeline :items="$timeline" empty-text="Povijest se puni automatski čim mijenjate status, dealove ili ponude." />
</section>
@endsection
