@extends('layouts.app')
@section('title',$quote->exists?'Uredi ponudu':'Nova ponuda')
@section('content')
@php($formItems = old('items', $quote->exists ? $quote->items->map(fn($i)=>['description'=>$i->description,'quantity'=>$i->quantity,'unit'=>$i->unit,'unit_price'=>$i->unit_price])->all() : [['description'=>'','quantity'=>1,'unit'=>'kom','unit_price'=>0]]))
<div class="form-shell"><x-page-header eyebrow="PONUDE" :title="$quote->exists?'Uredi ponudu':'Nova ponuda'" description="Jasna ponuda s potpunim poslovnim kontekstom i automatskim izračunom." /><x-form-errors />
<form method="POST" action="{{ $quote->exists?route('quotes.update',$quote):route('quotes.store') }}" id="quote-form">@csrf @if($quote->exists)@method('PUT')@endif
<section class="form-card"><div class="form-section-head"><span>01</span><div><h2>Podaci ponude</h2><p>Dokument, status i valjanost</p></div></div><div class="form-grid"><div class="field full"><span>Naslov ponude <em>*</em></span><input name="title" value="{{ old('title',$quote->title) }}" required></div><div class="field"><span>Status <em>*</em></span><select name="status">@foreach(App\Enums\QuoteStatus::cases() as $s)<option value="{{ $s->value }}" @selected(old('status',$quote->status?->value??'draft')===$s->value)>{{ $s->label() }}</option>@endforeach</select></div><div class="field"><span>Deal</span><select name="deal_id"><option value="">— Bez deala —</option>@foreach($deals as $deal)<option value="{{ $deal->id }}" @selected((string)old('deal_id',$quote->deal_id)===(string)$deal->id)>{{ $deal->title }}</option>@endforeach</select></div><div class="field"><span>Tvrtka</span><select name="company_id"><option value="">— Bez tvrtke —</option>@foreach($companies as $company)<option value="{{ $company->id }}" @selected((string)old('company_id',$quote->company_id)===(string)$company->id)>{{ $company->name }}</option>@endforeach</select></div><div class="field"><span>Kontakt</span><select name="contact_id"><option value="">— Bez kontakta —</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected((string)old('contact_id',$quote->contact_id)===(string)$contact->id)>{{ $contact->full_name }}</option>@endforeach</select></div><div class="field"><span>Datum izdavanja <em>*</em></span><input type="date" name="issue_date" value="{{ old('issue_date',$quote->issue_date?->format('Y-m-d')) }}" required></div><div class="field"><span>Vrijedi do</span><input type="date" name="valid_until" value="{{ old('valid_until',$quote->valid_until?->format('Y-m-d')) }}"></div></div></section>
<section class="form-card"><div class="form-section-head"><span>02</span><div><h2>Stavke</h2><p>Proizvodi i usluge uključeni u ponudu</p></div></div><div class="data-table-wrap"><table class="items-table"><thead><tr><th>Opis</th><th>Količina</th><th>Jedinica</th><th>Jed. cijena</th><th>Ukupno</th><th></th></tr></thead><tbody id="quote-items">@foreach($formItems as $index=>$item)<tr data-item><td><input class="item-desc" name="items[{{ $index }}][description]" value="{{ $item['description'] }}" placeholder="Opis usluge" required></td><td><input class="item-small" type="number" min="0.01" step="0.01" name="items[{{ $index }}][quantity]" value="{{ $item['quantity'] }}" data-quantity required></td><td><input class="item-small" name="items[{{ $index }}][unit]" value="{{ $item['unit'] }}" required></td><td><input type="number" min="0" step="0.01" name="items[{{ $index }}][unit_price]" value="{{ $item['unit_price'] }}" data-price required></td><td><strong data-line-total>0,00 €</strong></td><td><button type="button" class="remove-item" data-remove title="Ukloni">×</button></td></tr>@endforeach</tbody></table></div><button type="button" class="add-item" id="add-item">＋ Dodaj stavku</button>
<div class="quote-live-total"><div class="total-line"><span>Međuzbroj</span><strong data-subtotal>0,00 €</strong></div><div class="total-line"><span>Popust</span><strong data-discount-total>0,00 €</strong></div><div class="total-line"><span>PDV</span><strong data-tax-total>0,00 €</strong></div><div class="total-line grand"><span>Ukupno</span><strong data-grand-total>0,00 €</strong></div></div></section>
<section class="form-card"><div class="form-section-head"><span>03</span><div><h2>Uvjeti i obračun</h2><p>Valuta, porez i završne napomene</p></div></div><div class="form-grid"><div class="field"><span>Valuta <em>*</em></span><select name="currency" data-currency><option>EUR</option><option @selected(old('currency',$quote->currency)==='USD')>USD</option><option @selected(old('currency',$quote->currency)==='GBP')>GBP</option></select></div><div class="field"><span>Popust (%)</span><input type="number" min="0" max="100" step="0.01" name="discount_percent" value="{{ old('discount_percent',$quote->discount_percent??0) }}" data-discount></div><div class="field"><span>PDV (%)</span><input type="number" min="0" max="100" step="0.01" name="tax_percent" value="{{ old('tax_percent',$quote->tax_percent??25) }}" data-tax></div><div class="field full"><span>Napomena klijentu</span><textarea name="notes">{{ old('notes',$quote->notes) }}</textarea></div><div class="field full"><span>Uvjeti plaćanja</span><textarea name="terms" placeholder="npr. Plaćanje u roku 15 dana od izdavanja računa.">{{ old('terms',$quote->terms) }}</textarea></div></div></section>
<div class="form-footer"><a class="ghost-btn" href="{{ $quote->exists?route('quotes.show',$quote):route('quotes.index') }}">Odustani</a><button class="primary-btn">{{ $quote->exists?'Spremi promjene':'Izradi ponudu' }} →</button></div></form></div>
@endsection
@push('scripts')
<script>
(()=>{const body=document.querySelector('#quote-items'),add=document.querySelector('#add-item'),form=document.querySelector('#quote-form');let index={{ count($formItems) }};const money=(n)=>new Intl.NumberFormat('hr-HR',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n)+' '+(form.querySelector('[data-currency]').value||'EUR');function calc(){let subtotal=0;body.querySelectorAll('[data-item]').forEach(row=>{const total=(parseFloat(row.querySelector('[data-quantity]').value)||0)*(parseFloat(row.querySelector('[data-price]').value)||0);subtotal+=total;row.querySelector('[data-line-total]').textContent=money(total)});const discount=subtotal*(parseFloat(form.querySelector('[data-discount]').value)||0)/100,tax=(subtotal-discount)*(parseFloat(form.querySelector('[data-tax]').value)||0)/100;form.querySelector('[data-subtotal]').textContent=money(subtotal);form.querySelector('[data-discount-total]').textContent='− '+money(discount);form.querySelector('[data-tax-total]').textContent=money(tax);form.querySelector('[data-grand-total]').textContent=money(subtotal-discount+tax)}function bind(){body.querySelectorAll('input').forEach(i=>i.oninput=calc);body.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(body.children.length>1)b.closest('tr').remove();calc()})}add.onclick=()=>{body.insertAdjacentHTML('beforeend',`<tr data-item><td><input class="item-desc" name="items[${index}][description]" placeholder="Opis usluge" required></td><td><input class="item-small" type="number" min="0.01" step="0.01" name="items[${index}][quantity]" value="1" data-quantity required></td><td><input class="item-small" name="items[${index}][unit]" value="kom" required></td><td><input type="number" min="0" step="0.01" name="items[${index}][unit_price]" value="0" data-price required></td><td><strong data-line-total>0,00 EUR</strong></td><td><button type="button" class="remove-item" data-remove>×</button></td></tr>`);index++;bind();calc()};form.querySelectorAll('[data-discount],[data-tax],[data-currency]').forEach(i=>i.oninput=calc);bind();calc()})();
</script>
@endpush
