@extends('layouts.app')
@section('title',$deal->exists?'Uredi deal':'Novi deal')
@section('content')
<div class="form-shell"><x-page-header eyebrow="DEALOVI" :title="$deal->exists?'Uredi deal':'Novi deal'" description="Definirajte priliku, očekivanu vrijednost i sljedeću fazu." /><x-form-errors />
<form method="POST" action="{{ $deal->exists?route('deals.update',$deal):route('deals.store') }}">@csrf @if($deal->exists)@method('PUT')@endif
<section class="form-card"><div class="form-section-head"><span>01</span><div><h2>Prilika</h2><p>Glavni kontekst deala</p></div></div><div class="form-grid"><div class="field full"><span>Naziv deala <em>*</em></span><input name="title" value="{{ old('title',$deal->title) }}" placeholder="npr. Redizajn korisničkog portala" required></div><div class="field"><span>Tvrtka</span><select name="company_id"><option value="">— Bez tvrtke —</option>@foreach($companies as $company)<option value="{{ $company->id }}" @selected((string)old('company_id',$deal->company_id)===(string)$company->id)>{{ $company->name }}</option>@endforeach</select></div><div class="field"><span>Glavni kontakt</span><select name="contact_id"><option value="">— Bez kontakta —</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected((string)old('contact_id',$deal->contact_id)===(string)$contact->id)>{{ $contact->full_name }}</option>@endforeach</select></div><div class="field"><span>Faza <em>*</em></span><select name="stage">@foreach(App\Enums\DealStage::cases() as $s)<option value="{{ $s->value }}" @selected(old('stage',$deal->stage?->value??'qualification')===$s->value)>{{ $s->label() }}</option>@endforeach</select></div><div class="field"><span>Očekivano zatvaranje</span><input type="date" name="expected_close_date" value="{{ old('expected_close_date',$deal->expected_close_date?->format('Y-m-d')) }}"></div></div></section>
<section class="form-card"><div class="form-section-head"><span>02</span><div><h2>Vrijednost</h2><p>Financijski potencijal i vjerojatnost</p></div></div><div class="form-grid"><div class="field"><span>Vrijednost <em>*</em></span><input type="number" min="0" step="0.01" name="value" value="{{ old('value',$deal->value??0) }}" required></div><div class="field"><span>Valuta <em>*</em></span><select name="currency"><option>EUR</option><option @selected(old('currency',$deal->currency)==='USD')>USD</option><option @selected(old('currency',$deal->currency)==='GBP')>GBP</option></select></div><div class="field"><span>Vjerojatnost (%) <em>*</em></span><input type="number" min="0" max="100" name="probability" value="{{ old('probability',$deal->probability??10) }}"></div><div class="field full"><span>Opis i sljedeći koraci</span><textarea name="description">{{ old('description',$deal->description) }}</textarea></div></div></section>
<div class="form-footer"><a class="ghost-btn" href="{{ $deal->exists?route('deals.show',$deal):route('deals.index') }}">Odustani</a><button class="primary-btn">{{ $deal->exists?'Spremi promjene':'Izradi deal' }} →</button></div></form></div>
@endsection
